version: "3.8"

services:
  redis:
    image: redis:alpine
    container_name: redis_server
    ports:
      - "6379:6379"
    volumes:
      - ./volumes/redis:/data
    restart: always

volumes:
  redis:
    driver: local
